-- remove plugin -- require('nvim-autopairs').setup()
-- remove plugin -- 
-- remove plugin -- local Rule = require 'nvim-autopairs.rule'
-- remove plugin -- local npairs = require 'nvim-autopairs'
-- remove plugin -- 
-- remove plugin -- npairs.add_rule(Rule('$$', '$$', 'tex'))
